### ISSUE TITLE
search/replace within mail bodies

### ISSUE THREAD

**Issue by traut21** [raforg/textmail#1] opened 2022-03-21 12:34 UTC
thanks, textmail seems to be an awesome helper.

However, what I'd like to have is some filter for message bodies

e.g. to remove trailing fullquotes with at least ten lines starting with ">" before the end of the body.

Is there a chance to perform an sed script on each mail body?

**Comment by raforg** [comment] 2022-03-22 02:44
Yes. The -C option lets you supply an external program to act as a translator. However, it wasn't designed for modifying text/plain attachments, so unfortunately, you'd (probably) need to run textmail to convert/replace any HTML with plain text, and then pipe it through another textmail with -C.

I've attached a perl script that I think will do what you want like this:

    $ opts=
    $ textmail $opts < mbox.in | textmail $opts -C text/plain:stripquotes > mbox.out

Carefully decide what textmail options you want. It's very aggressive by default.
And make sure you have the requisite translator programs with: textmail -?

There is a slight bug. It "moves" blank lines after a quoteblock to before it (which is noticeable when the quoteblock is small enough to be retained). Hopefully, that's OK.
It means that multiple quoteblocks separated only by blank lines are treated as a single quoteblock.

[stripquotes.txt](https://github.com/raforg/textmail/files/8320540/stripquotes.txt)

**Comment by traut21** [comment] 2022-03-22 06:42
Am 2022-03-22 um 03:44 schrieb raf:
>
> Yes. The -C option lets you supply an external program to act as a 
> translator. However, it wasn't designed for modifying text/plain 
> attachments, so unfortunately, you'd (probably) need to run textmail 
> to convert/replace any HTML with plain text, and then pipe it through 
> another textmail with -C.
>
> I've attached a perl script that I think will do what you want like this:
>
> |$ opts= $ textmail $opts < mbox.in | textmail $opts -C 
> text/plain:stripquotes > mbox.out |

|That's great - it does handle the signature properly, too. And I could 
modify this script to get rid of certain signatures as well.


|
>
> Carefully decide what textmail options you want. It's very aggressive 
> by default.
> And make sure you have the requisite translator programs with: textmail -?
>

I don't have docx2txt yet, which was no problem. I can live with the -W 
option.
> There is a slight bug. It "moves" blank lines after a quoteblock to 
> before it (which is noticeable when the quoteblock is small enough to 
> be retained). Hopefully, that's OK.

That should be fixable.
>
> It means that multiple quoteblocks separated only by blank lines are 
> treated as a single quoteblock.
>

which is more important to me.

Thanks!
Martin

**Comment by traut21** [comment] 2022-03-22 07:23
Up to now I did not find out yet how to use textmail with full mbox 
files - but I called

   textmail $MBOX

only. That's why I wondered whether I should use muss, getmail, procmail 
to pass mails to textmail one by one.

However, if textmail can handle full mbox files, how about some initial 
check function first, that would give some stats
* about acual attachments: type and count
* about weired encodings or stuff it can't handle yet
* about huge headers

my mail provider does insert huge X-UI-Filterresults: (124 lines with 75 
characters each), but I have no overview about other huge headers yet. I 
noticed some large AVG antivirus checks redently, which added large 
headers from the sender of their own.

A stats count would be very nice to tell me
* about the number of messages (which should be the same as given from 
an e-mail-programm)
* the total count of header lines
* the e.g. 10 highest amounts of header comsumption
   ...which should be references, and I don't mind if 10 references 
within one messages are counted as one

But it would tell me about headers I should really get rid of.

**Comment by raforg** [comment] 2022-03-23 06:10
Here's a program that'll show some stats on headers (counts, total/average lines and size) and attachments (count/size by mimetype).

[mboxstats.txt](https://github.com/raforg/textmail/files/8330190/mboxstats.txt)

textmail does process mbox files (or individual emails). If you can send me a small reproducible example of it not doing so (by email is fine), I can investigate.

**Comment by traut21** [comment] 2022-03-23 07:22
It works better now.

It failed sometimes on

         return join '', map { $_->[1] } sort { my ($ad) = $a->[0] =~ 
/(\d+)/; my ($bd) = $b->[0] =~ /(\d+)/; $ad <=> $bd } @p;

Use of uninitialized value $bd in numeric comparison (<=>) at 
/usr/local/bin/textmail line 754, <> line 64649.
Use of uninitialized value $ad in numeric comparison (<=>) at 
/usr/local/bin/textmail line 754, <> line 64649.

It failed fatally after 793 of 21019 messages at
Can't use an undefined value as an ARRAY reference at 
/usr/local/bin/textmail line 793, <> line 245145.

             return [@{$m->{mime_parts}}] unless defined $p;

**Comment by raforg** [comment] 2022-03-27 02:40
On Wed, Mar 23, 2022 at 12:22:44AM -0700, traut21 ***@***.***> wrote:

Thanks.

> It works better now.
> 
> It failed sometimes on
> 
>          return join '', map { $_->[1] } sort { my ($ad) = $a->[0] =~ 
> /(\d+)/; my ($bd) = $b->[0] =~ /(\d+)/; $ad <=> $bd } @p;
> 
> Use of uninitialized value $bd in numeric comparison (<=>) at 
> /usr/local/bin/textmail line 754, <> line 64649.
> Use of uninitialized value $ad in numeric comparison (<=>) at 
> /usr/local/bin/textmail line 754, <> line 64649.

That's strange. Your line numbers are one off compared to mine.
For me, that line of code is line 753, and the one below is 792.

Anyway, it would be really helpful if you could show me at
least line 64649 of that input file. I expect it'll be a MIME
header with parameters that include continuations and/or a
character set/language (RFC2231). But that shouldn't be a problem,
so it'll be interesting to see. Being able to see the whole email
that contains line 64649 would be better. But it might not be
needed for this one.

> It failed fatally after 793 of 21019 messages at
> Can't use an undefined value as an ARRAY reference at 
> /usr/local/bin/textmail line 793, <> line 245145.
> 
>              return [@{$m->{mime_parts}}] unless defined $p;

That one's really strange. I can't see how that can happen, just
looking at the code. It would be really helpful if you could
send me the entire message that contains line 245145 of that input
file. If you are willing to, you can send it to the email address
in the git logs. I'm sure you could redact all of the body text and
any attachment content and any sensitive header content. I just need
all of the headers and mime structure to be present. If you do this,
just make sure that it produces the same problems.

**Comment by traut21** [comment] 2022-03-27 09:33
Am 27.03.22 um 04:40 schrieb raf:
> On Wed, Mar 23, 2022 at 12:22:44AM -0700, traut21 ***@***.***> wrote:
>
> Thanks.
>
> > It works better now.
> >
> > It failed sometimes on
> >
> >         return join '', map { $_->[1] } sort { my ($ad) = $a->[0] =~
> > /(\d+)/; my ($bd) = $b->[0] =~ /(\d+)/; $ad <=> $bd } @p;
> >
> > Use of uninitialized value $bd in numeric comparison (<=>) at
> > /usr/local/bin/textmail line 754, <> line 64649.
> > Use of uninitialized value $ad in numeric comparison (<=>) at
> > /usr/local/bin/textmail line 754, <> line 64649.
>
> That's strange. Your line numbers are one off compared to mine.
> For me, that line of code is line 753, and the one below is 792.

That's why I named both line number and content - I had added an extra
line for the From separator, while I commented yours, which checked for
the RfC recommended mail address.
> Anyway, it would be really helpful if you could show me at
> least line 64649 of that input file. I expect it'll be a MIME
> header with parameters that include continuations and/or a
> character set/language (RFC2231). But that shouldn't be a problem,
> so it'll be interesting to see. Being able to see the whole email
> that contains line 64649 would be better. But it might not be
> needed for this one.
>
> > It failed fatally after 793 of 21019 messages at
> > Can't use an undefined value as an ARRAY reference at
> > /usr/local/bin/textmail line 793, <> line 245145.
> >
> >             return [@{$m->{mime_parts}}] unless defined $p;
>
> That one's really strange. I can't see how that can happen, just
> looking at the code. It would be really helpful if you could
> send me the entire message that contains line 245145 of that input
> file. If you are willing to, you can send it to the email address
> in the git logs. I'm sure you could redact all of the body text and
> any attachment content and any sensitive header content. I just need
> all of the headers and mime structure to be present. If you do this,
> just make sure that it produces the same problems.

I'll have a look. Unfortunately, I tried to update mutt etc. for better
mime filters. But port on my old MacOS caused some severe trouble,
destroying my installation. I have a recent backup, but the restore
mechanism does not work yet. So it may take some days until I'll have my
access back to my mail archives.

**Comment by raforg** [comment] 2022-03-28 02:19
On Sun, Mar 27, 2022 at 02:33:21AM -0700, traut21 ***@***.***> wrote:

> Am 27.03.22 um 04:40 schrieb raf:
> > >
> > > Use of uninitialized value $bd in numeric comparison (<=>) at
> > > /usr/local/bin/textmail line 754, <> line 64649.
> > > Use of uninitialized value $ad in numeric comparison (<=>) at
> > > /usr/local/bin/textmail line 754, <> line 64649.
> >
> > That's strange. Your line numbers are one off compared to mine.
> > For me, that line of code is line 753, and the one below is 792.
> 
> That's why I named both line number and content - I had added an extra
> line for the From separator, while I commented yours, which checked for
> the RfC recommended mail address.

If you've made changes to the source code, it would be helpful
to let me know exactly what the change was, and why it was made,
and what effect it had.

Are you saying that your mbox is malformed? The check for the mbox From_
header on line 575 doesn't expect an email address. Any non-whitespace
characters will do for that part. It does expect a timestamp in a
particular format, though.

If there is something wrong with that check, showing me the From_ header
in question would be good. Looking at the pattern, I can imagine some
invalid things that maybe it could match but won't. But without seeing what
it is expected to match in your file, I can't really change it blind.
I'd just be guessing.

Also note that technically, there are about five different mbox formats.
The one supported by textmail is known as "mboxrd". Maybe that's significant.

> > Anyway, it would be really helpful if you could show me at
> > least line 64649 of that input file. I expect it'll be a MIME
> > header with parameters that include continuations and/or a
> > character set/language (RFC2231). But that shouldn't be a problem,
> > so it'll be interesting to see. Being able to see the whole email
> > that contains line 64649 would be better. But it might not be
> > needed for this one.
> >
> > > It failed fatally after 793 of 21019 messages at
> > > Can't use an undefined value as an ARRAY reference at
> > > /usr/local/bin/textmail line 793, <> line 245145.
> > >
> > >             return [@{$m->{mime_parts}}] unless defined $p;
> >
> > That one's really strange. I can't see how that can happen, just
> > looking at the code. It would be really helpful if you could
> > send me the entire message that contains line 245145 of that input
> > file. If you are willing to, you can send it to the email address
> > in the git logs. I'm sure you could redact all of the body text and
> > any attachment content and any sensitive header content. I just need
> > all of the headers and mime structure to be present. If you do this,
> > just make sure that it produces the same problems.
> 
> I'll have a look. Unfortunately, I tried to update mutt etc. for better
> mime filters. But port on my old MacOS caused some severe trouble,
> destroying my installation. I have a recent backup, but the restore
> mechanism does not work yet. So it may take some days until I'll have my
> access back to my mail archives.

Good luck.

**Comment by traut21** [comment] 2022-03-28 05:30
Am 28.03.22 um 04:19 schrieb raf:
> On Sun, Mar 27, 2022 at 02:33:21AM -0700, traut21 ***@***.***> wrote:
>
>  > Am 27.03.22 um 04:40 schrieb raf:
>  > > >
>  > > > Use of uninitialized value $bd in numeric comparison (<=>) at
>  > > > /usr/local/bin/textmail line 754, <> line 64649.
>  > > > Use of uninitialized value $ad in numeric comparison (<=>) at
>  > > > /usr/local/bin/textmail line 754, <> line 64649.
>  > >
>  > > That's strange. Your line numbers are one off compared to mine.
>  > > For me, that line of code is line 753, and the one below is 792.
>  >
>  > That's why I named both line number and content - I had added an extra
>  > line for the From separator, while I commented yours, which checked for
>  > the RfC recommended mail address.
>
> If you've made changes to the source code, it would be helpful
> to let me know exactly what the change was, and why it was made,
> and what effect it had.
>
> Are you saying that your mbox is malformed? The check for the mbox From_
> header on line 575 doesn't expect an email address. Any non-whitespace
> characters will do for that part. It does expect a timestamp in a
> particular format, though.

So you did not receive my sample mailbox from 22.03.22, 16:58 and my
reply from 23.03.22, 07:24 which had told you
+++
mboxstats does not recognize the email delimiter, such as

 From - Mon Jan 16 14:34:50 2017

within the mbox files.
+++

...a mailbox format which does not include the sender's mail within the
mbox From separator.

> If there is something wrong with that check, showing me the From_ header
> in question would be good. Looking at the pattern, I can imagine some
> invalid things that maybe it could match but won't. But without seeing what
> it is expected to match in your file, I can't really change it blind.
> I'd just be guessing.

Here it was again: "From - Mon Jan 16 14:34:50 2017"

> Also note that technically, there are about five different mbox formats.
> The one supported by textmail is known as "mboxrd". Maybe that's
> significant.

It is - it's the reason why textmail failed to work here. Both mutt and
Thunderbird do understand this mbox format here. That's why I did not
expect any mailbox problem.

**Comment by raforg** [comment] 2022-03-29 02:52
On Sun, Mar 27, 2022 at 10:30:12PM -0700, traut21 ***@***.***> wrote:

> So you did not receive my sample mailbox from 22.03.22, 16:58 and my
> reply from 23.03.22, 07:24 which had told you
> +++
> mboxstats does not recognize the email delimiter, such as
> 
>  From - Mon Jan 16 14:34:50 2017
> 
> within the mbox files.
> +++
> 
> ...a mailbox format which does not include the sender's mail within the
> mbox From separator.

Sorry. I missed it. I can find the 22.03.22, 16:58 one.
Not sure what happened to the second one. Thanks for that.

The bug was the "address" being a single character
combined with there only being a single space between
it and the following date. Two characters or two spaces
would have worked. There are two spaces between the
address and date in all of my incoming mail, but it
can't be a requirement because mutt uses a single space
there for my outgoing mail. Maybe the two spaces is a
procmail thing.

I've committed a fix for it. Thanks again.

**Closed as completed** 2023-03-13 12:55 UTC
